# Generated by Django 5.1.4 on 2024-12-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbeto', '0004_rename_familiares_familiare_rename_regalos_regalo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiare',
            new_name='Familiar',
        ),
    ]
