# Generated by Django 5.1.4 on 2024-12-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbeto', '0005_rename_familiare_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('plato', models.CharField(max_length=255)),
                ('bebida', models.CharField(max_length=255)),
            ],
        ),
    ]
