# Generated by Django 5.1.4 on 2024-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbeto', '0007_menu_apellido_regalo_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('icono', models.ImageField(max_length=255, upload_to='')),
                ('fecha', models.DateField(max_length=255)),
                ('nick', models.CharField(max_length=255)),
            ],
        ),
    ]
