# Generated by Django 5.1.4 on 2024-12-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbeto', '0008_misblogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MisBlogs',
            new_name='MisBlog',
        ),
    ]
