# Generated by Django 5.1.4 on 2024-12-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbeto', '0009_rename_misblogs_misblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misblog',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos_blog'),
        ),
    ]
